### ISSUE TITLE
step1_train_teacher.py", line 123

### ISSUE THREAD

**Issue by 237014845** [cvlab-yonsei/PISR#17]
Traceback (most recent call last):
  File "step1_train_teacher.py", line 242, in <module>
    main()
  File "step1_train_teacher.py", line 236, in main
    run(config)
  File "step1_train_teacher.py", line 204, in run
    writer, visualizer, last_epoch+1)
  File "step1_train_teacher.py", line 153, in train
    eval_type='val')
  File "step1_train_teacher.py", line 123, in evaluate_single_epoch
    avg_loss = total_loss / (i+1)
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by NeonLeexiang** [comment]
> Traceback (most recent call last):
> File "step1_train_teacher.py", line 242, in 
> main()
> File "step1_train_teacher.py", line 236, in main
> run(config)
> File "step1_train_teacher.py", line 204, in run
> writer, visualizer, last_epoch+1)
> File "step1_train_teacher.py", line 153, in train
> eval_type='val')
> File "step1_train_teacher.py", line 123, in evaluate_single_epoch
> avg_loss = total_loss / (i+1)
> UnboundLocalError: local variable 'i' referenced before assignment

maybe you can define i and then use it in the training process, that's because it does not be defined outer the for circulation
